spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/cities_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: <username>
    password: <password>
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: "mysql"
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    banner-mode: "off"

logging:
  level:
    org:
      springframework: ERROR

management:
  endpoint:
    beans:
      enabled: true
    metrics:
      enabled: true
    health:
      showDetails: "always"
  server:
    port: 9001
    servlet:
      contextPath: "/api/v1/cities/"
  endpoints:
    web:
      exposure:
        include: "*"
