spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      #spring.data.mongodb.authentication-database=[authentication_database]
      #spring.data.mongodb.username=[username]
      #spring.data.mongodb.password=[password]
      database: pet_store

management:
  endpoint:
    beans:
      enabled: true
    metrics:
      enabled: true
    health:
      showDetails: "always"
  server:
    port: 9001
    servlet:
      contextPath: "/api/v1/pets/"
  endpoints:
    web:
      exposure:
        include: "*"